# Generated by Django 6.0.3 on 2026-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rendezvous_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='rdv',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_rdv',
            field=models.DateField(blank=True, help_text='Date souhaitée pour le rendez-vous', null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='message',
            field=models.TextField(blank=True, help_text='Message ou motif du rendez-vous', null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
