# Generated by Django 6.0.3 on 2026-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_rendezvous_rdv_rendezvous_date_rdv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ex: 1.0.1', max_length=20)),
                ('apk_file', models.FileField(blank=True, help_text="Le fichier APK de l'application (optionnel si URL externe fournie)", null=True, upload_to='apks/updates/')),
                ('external_url', models.URLField(blank=True, help_text='URL externe vers le fichier APK (Cloud, etc.)', null=True)),
                ('release_notes', models.TextField(blank=True, help_text='Les nouveautés de cette mise à jour', null=True)),
                ('force_update', models.BooleanField(default=False, help_text="Cocher pour obliger l'utilisateur à mettre à jour")),
                ('is_active', models.BooleanField(default=True, help_text='Est-ce la version actuellement déployée ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Version de l'application",
                'verbose_name_plural': "Versions de l'application",
                'ordering': ['-created_at'],
            },
        ),
    ]
