# Generated by Django 6.0.6 on 2026-06-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_verificationcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['identifier', 'purpose', 'is_used'], name='api_verific_identif_139074_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['code'], name='api_verific_code_91e0db_idx'),
        ),
    ]
