# Generated by Django 6.0.1 on 2026-03-29 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(default='Eglise CIMPP', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('orateur', models.CharField(max_length=100)),
                ('interprete', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Predication',
                'verbose_name_plural': 'Predications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('subjet', models.CharField(max_length=50)),
                ('temoignage', models.TextField()),
            ],
            options={
                'verbose_name': 'Temoignage',
                'verbose_name_plural': 'Temoignages',
            },
        ),
    ]
