# Generated by Django 6.0.3 on 2026-04-10 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(default='Eglise CIMPP', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_couverture', models.ImageField(upload_to='predications/')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField()),
                ('url_video', models.URLField(blank=True)),
                ('resume', models.TextField(blank=True)),
                ('verset_principal', models.CharField(blank=True, max_length=100)),
                ('contenu', models.TextField(blank=True)),
                ('predicateur', models.CharField(max_length=200, verbose_name='Preacher')),
                ('interprete', models.CharField(blank=True, max_length=200, null=True, verbose_name='Interprete')),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predication',
                'verbose_name_plural': 'Predications',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('subjet', models.CharField(max_length=50)),
                ('temoignage', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Temoignage',
                'verbose_name_plural': 'Temoignages',
            },
        ),
    ]
