# Generated by Django 6.0.3 on 2026-04-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predication',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
