# Generated by Django 6.0.1 on 2026-03-29 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predication',
            options={'ordering': ['date'], 'verbose_name': 'Predication', 'verbose_name_plural': 'Predications'},
        ),
        migrations.RemoveField(
            model_name='predication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='predication',
            name='name',
        ),
        migrations.RemoveField(
            model_name='predication',
            name='orateur',
        ),
        migrations.AddField(
            model_name='predication',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predication',
            name='predicateur',
            field=models.CharField(default='', max_length=200, verbose_name='Preacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predication',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predication',
            name='titre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='predication',
            name='url_video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='predication',
            name='verset_principal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='predication',
            name='interprete',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Interprete'),
        ),
        migrations.AlterField(
            model_name='predication',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
