# Generated by Django 6.0.1 on 2026-03-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_predication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predication',
            name='img_couverture',
            field=models.ImageField(default='', upload_to='predications/'),
            preserve_default=False,
        ),
    ]
