# Generated by Django 6.0.3 on 2026-04-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_predication_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeHebdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('horaire', models.CharField(max_length=20)),
                ('activite', models.CharField(max_length=100)),
                ('icone', models.CharField(default='fa-solid fa-hands-praying', max_length=50)),
                ('badge_special', models.BooleanField(default=False)),
                ('salle', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Pour trier les activités')),
            ],
            options={
                'verbose_name': 'Programme Hebdo',
                'verbose_name_plural': 'Programmes Hebdo',
                'ordering': ['ordre'],
            },
        ),
    ]
