# Generated by Django 6.0.3 on 2026-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_programmehebdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Culte en Direct', max_length=200)),
                ('url', models.URLField(help_text='URL du flux (ex: YouTube Live)')),
                ('is_live', models.BooleanField(default=False, help_text='Activer si le direct est en cours')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direct',
                'verbose_name_plural': 'Direct',
            },
        ),
        migrations.AlterModelOptions(
            name='programmehebdo',
            options={'verbose_name': 'Direct', 'verbose_name_plural': 'Direct'},
        ),
    ]
