# Generated by Django 6.0.1 on 2026-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_predication_img_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignages',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
