# Generated by Django 6.0.3 on 2026-05-02 18:27

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0004_livestream_alter_programmehebdo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmehebdo',
            options={'verbose_name': 'Programme Hebdo', 'verbose_name_plural': 'Programmes Hebdo'},
        ),
        migrations.AddField(
            model_name='livestream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='predication',
            name='url_video',
            field=models.URLField(blank=True, help_text='URL de la vidéo YouTube ou Facebook'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('vimeo', 'Vimeo'), ('tiktok', 'TikTok')], default='youtube', max_length=20)),
                ('url', models.URLField(help_text="Collez l'URL de la vidéo ici")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
            },
            bases=(models.Model, main.models.VideoMixin),
        ),
    ]
