# Generated by Django 6.0.3 on 2026-05-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='predication',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
