# Generated by Django 6.0.6 on 2026-06-20 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_predication_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='predication',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='temoignages',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
