"""
Django settings for CIMPP project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import cloudinary #importer en premierer position avec os

import os
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['*']

# ──────────────────────────────────────────────
# CLOUDINARY — initialisation explicite
# ──────────────────────────────────────────────

cloudinary.config(
    cloud_name =os.getenv("CLOUD_NAME"),
    api_key =os.getenv("API_KEY"),
    api_secret =os.getenv('API_SECRET'),
    secure =True
)


CLOUDINARY_STORAGE ={
    'CLOUD_NAME':os.getenv("CLOUD_NAME"),
    'API_KEY':os.getenv("API_KEY"),
    'API_SECRET':os.getenv("API_SECRET"),
    'RESSOURCE_TYPE':'auto'  # avec auto cloudinary detecte lui meme si le fichier est une image,une video ou fichier brute



}



# ──────────────────────────────────────────────
# STOCKAGE DES FICHIERS MEDIA → CLOUDINARY
# ──────────────────────────────────────────────

# On désactive Cloudinary pour le stockage par défaut
#DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Nouvelle configuration via django-storages
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Force Django à signer chaque lien (contourne le mode Private de MinIO)
AWS_QUERYSTRING_AUTH = True

# Paramètres de connexion MinIO
#
AWS_ACCESS_KEY_ID = 'GK36585bb667d2b9df10a292c8'
AWS_SECRET_ACCESS_KEY = 'bd07599fd632c59a047487893473fc56772980fa61f0b79d5eda15c0955193df'
AWS_STORAGE_BUCKET_NAME = 'video' #le bucket name creer 
AWS_S3_ENDPOINT_URL ='http://192.168.1.69:3900'# L'adresse de ton Lab Windows

AWS_S3_REGION_NAME = "garage"

AWS_S3_ADDRESSING_STYLE = "path"
AWS_DEFAULT_ACL = None


# Paramètres spécifiques pour éviter les erreurs en local
AWS_S3_SECURE_URLS = False       # Pas de HTTPS
AWS_QUERYSTRING_AUTH = False     # Garde les liens simples (sans jetons complexes)
AWS_S3_FILE_OVERWRITE = False    # Ne pas écraser si le nom est identique

AWS_S3_CUSTOM_DOMAIN = '127.0.0.1:8000/media'
AWS_QUERYSTRING_AUTH = False
AWS_S3_URL_PROTOCOL = 'http:'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',                   # ← APRÈS staticfiles
    'main',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'api',
    'drf_spectacular',
]

# if DEBUG:
#     INSTALLED_APPS += ["django_browser_reload"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# if DEBUG:
    # MIDDLEWARE += ["django_browser_reload.middleware.BrowserReloadMiddleware"]

ROOT_URLCONF = 'CIMPP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CIMPP.wsgi.application'

# ──────────────────────────────────────────────
# BASE DE DONNÉES — Aiven MySQL
# ──────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':     os.getenv('DB_NAME'),
        #CIMPP_DB
        'USER':     os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST':     os.getenv('DB_HOST'),
        'PORT':     os.getenv('DB_PORT'),
        'CONN_MAX_AGE': 600, # Garde la connexion ouverte 10 minutes
        'OPTIONS': {
            'ssl': {'ca': None},
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static/']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
# MEDIA_URL = 'media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'api.backends.PhoneOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CIMPP API',
    'DESCRIPTION': 'Documentation interactive de l\'API du Centre International de Mission Prophétique et de la Parole (CIMPP).',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Autres configurations si besoin
}

# Simple JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
